import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/Colors';

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: Colors.background },
  list: { paddingHorizontal: 20 },
  header: { paddingTop: 16, paddingBottom: 20 },
  title: { fontSize: 28, lineHeight: 36, fontWeight: '800', color: Colors.text },
  subtitle: { fontSize: 14, lineHeight: 21, color: Colors.subtext, marginTop: 6 },
  petRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 18, marginBottom: 16 },
  petName: { flex: 1, minWidth: 0, fontSize: 17, fontWeight: '700', color: Colors.text },
  privateText: { fontSize: 12, color: Colors.subtext },
  controls: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  month: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    backgroundColor: Colors.surface,
    borderRadius: 16,
  },
  monthText: { color: Colors.text, fontSize: 17, fontWeight: '700', textAlign: 'center' },
  iconButton: {
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: Colors.surface,
  },
  filters: { gap: 8, paddingTop: 16, paddingBottom: 4 },
  filter: {
    paddingHorizontal: 14,
    minHeight: 44,
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  filterActive: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  filterText: { fontSize: 13, color: Colors.text, fontWeight: '600' },
  switchRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    marginTop: 12,
    flexWrap: 'wrap',
  },
  switchLabel: { flex: 1, minWidth: 170, color: Colors.subtext, fontSize: 13, lineHeight: 19 },
  week: {
    paddingVertical: 14,
    backgroundColor: Colors.background,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  weekTitle: { flex: 1, fontSize: 15, lineHeight: 22, fontWeight: '700', color: Colors.text },
  photoRow: { flexDirection: 'row', gap: 12, marginBottom: 18 },
  image: {
    aspectRatio: 1,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: Colors.peachSoft,
  },
  placeholder: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 8, padding: 12 },
  placeholderText: { color: Colors.subtext, fontSize: 12, textAlign: 'center', lineHeight: 18 },
  caption: { color: Colors.text, fontSize: 12, lineHeight: 18, marginTop: 7 },
  captionSub: { color: Colors.subtext, fontSize: 12, lineHeight: 17, marginTop: 1 },
  empty: { alignItems: 'center', paddingVertical: 44, paddingHorizontal: 16, gap: 12 },
  emptyTitle: { fontSize: 19, fontWeight: '700', color: Colors.text, textAlign: 'center' },
  emptyText: { fontSize: 14, lineHeight: 22, color: Colors.subtext, textAlign: 'center' },
  button: {
    minHeight: 44,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 18,
    backgroundColor: Colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: { color: Colors.text, fontWeight: '700', fontSize: 14 },
  footer: { gap: 10, paddingVertical: 12 },
  viewerHeader: { flexDirection: 'row', alignItems: 'center', padding: 16, gap: 12 },
  viewerBody: { paddingHorizontal: 20, paddingBottom: 24, gap: 16 },
  detailTitle: { fontSize: 20, lineHeight: 28, color: Colors.text, fontWeight: '700' },
  label: { color: Colors.subtext, fontSize: 13, lineHeight: 20 },
  body: { color: Colors.text, fontSize: 15, lineHeight: 24 },
  detailSection: { gap: 4 },
  primary: { backgroundColor: Colors.primary },
  primaryText: { color: Colors.surface },
  skeletonRow: { flexDirection: 'row', gap: 12, marginBottom: 18 },
  skeleton: { flex: 1, aspectRatio: 1, backgroundColor: Colors.border, borderRadius: 16 },
});
