import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/Colors';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  content: { paddingHorizontal: 18, paddingTop: 8, gap: 13 },
  header: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: Colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headingCopy: { flex: 1 },
  eyebrow: { color: Colors.primary, fontSize: 11, fontWeight: '800', letterSpacing: 1.3 },
  title: { marginTop: 2, color: Colors.text, fontSize: 24, fontWeight: '800' },
  headingIcon: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: Colors.successSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subtitle: { color: Colors.subtext, fontSize: 14, lineHeight: 21, marginBottom: 1 },
  searchRow: { flexDirection: 'row', gap: 9 },
  searchBox: {
    flex: 1,
    height: 48,
    borderRadius: 16,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  searchInput: { flex: 1, minWidth: 0, color: Colors.text, fontSize: 14, paddingVertical: 0 },
  locationButton: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: Colors.successSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationButtonBusy: { opacity: 0.55 },
  modeSwitch: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    padding: 4,
    borderRadius: 16,
    backgroundColor: '#EEE8DF',
  },
  modeOption: {
    minWidth: 84,
    height: 36,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  modeOptionActive: { backgroundColor: Colors.surface },
  modeText: { color: Colors.subtext, fontSize: 13, fontWeight: '700' },
  modeTextActive: { color: Colors.primary },
  mapFrame: {
    height: 300,
    overflow: 'hidden',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: '#E8E7DE',
  },
  map: { flex: 1 },
  mapEmptyHint: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    alignItems: 'center',
    backgroundColor: 'rgba(255, 249, 242, 0.94)',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  mapEmptyIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: Colors.successSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 5,
  },
  mapEmptyTitle: { color: Colors.text, fontSize: 14, fontWeight: '800' },
  mapEmptyText: { marginTop: 3, color: Colors.subtext, fontSize: 12, textAlign: 'center' },
  listHeadingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sectionTitle: { color: Colors.text, fontSize: 18, fontWeight: '800' },
  resultCount: { color: Colors.subtext, fontSize: 12, marginTop: 3 },
  clearLocation: { paddingVertical: 7, paddingHorizontal: 10 },
  clearLocationText: { color: Colors.success, fontSize: 12, fontWeight: '700' },
  hospitalRow: {
    minHeight: 82,
    padding: 13,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  hospitalIcon: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: Colors.successSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hospitalRowSelected: { borderColor: Colors.success, backgroundColor: Colors.successSoft },
  hospitalCopy: { flex: 1, minWidth: 0 },
  hospitalName: { color: Colors.text, fontSize: 15, fontWeight: '800' },
  hospitalAddress: { color: Colors.subtext, fontSize: 12, lineHeight: 17, marginTop: 3 },
  distanceText: { color: Colors.success, fontSize: 11, fontWeight: '700', marginTop: 4 },
  emptyCard: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 23,
    borderRadius: 18,
    backgroundColor: Colors.surfaceSoft,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  emptyTitle: { color: Colors.text, fontSize: 15, fontWeight: '800' },
  emptyText: {
    marginTop: 6,
    color: Colors.subtext,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
  },
  selectedCard: {
    padding: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    gap: 12,
  },
  selectedHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  sourceLabel: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  sourceLabelText: { flex: 1, color: Colors.subtext, fontSize: 11 },
  sourceMetaLink: { marginTop: -8 },
  sourceMetaText: { color: Colors.subtext, fontSize: 10, lineHeight: 15 },
  serviceHours: { color: Colors.text, fontSize: 12, fontWeight: '700' },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  serviceTag: {
    overflow: 'hidden',
    borderRadius: 9,
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: Colors.peachSoft,
    color: Colors.primary,
    fontSize: 11,
    fontWeight: '700',
  },
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
  secondaryAction: {
    flexGrow: 1,
    flexBasis: 100,
    minWidth: 100,
    minHeight: 44,
    borderRadius: 14,
    backgroundColor: Colors.successSoft,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  secondaryActionText: { color: Colors.success, fontSize: 13, fontWeight: '800' },
  primaryAction: {
    flexGrow: 1,
    flexBasis: 100,
    minWidth: 100,
    minHeight: 44,
    borderRadius: 14,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  primaryActionText: { color: '#FFF', fontSize: 13, fontWeight: '800' },
  sourceNote: { flexDirection: 'row', alignItems: 'flex-start', gap: 6, marginTop: 2 },
  sourceNoteText: { flex: 1, color: Colors.subtext, fontSize: 11, lineHeight: 16 },
  attributionRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', marginTop: -7 },
  attributionText: { color: Colors.subtext, fontSize: 10 },
  attributionLink: { color: Colors.success, fontSize: 10, textDecorationLine: 'underline' },
});
