/** 用途：用藥列表、表單、詳細頁共用樣式。 */
import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/Colors';
import {
  FORM_BUTTON_HEIGHT,
  FORM_BUTTON_RADIUS,
  FORM_FIELD_HEIGHT,
  FORM_FIELD_FONT_SIZE,
  FORM_FIELD_LABEL_FONT_SIZE,
  FORM_FIELD_LABEL_FONT_WEIGHT,
  FORM_FIELD_LABEL_MARGIN_BOTTOM,
  FORM_FIELD_LABEL_MARGIN_TOP,
  FORM_FIELD_RADIUS,
  FORM_PAGE_HORIZONTAL_PADDING,
} from '../../constants/FormTokens';

export const medicationStyles = StyleSheet.create({
  emptyBox: { alignItems: 'center', paddingVertical: 28 },
  emptyArtwork: { width: 82, height: 76, marginBottom: 10 },
  emptyHint: { color: '#887A6D', fontSize: 13, marginTop: 6, textAlign: 'center' },
  page: { paddingHorizontal: FORM_PAGE_HORIZONTAL_PADDING, paddingTop: 18, paddingBottom: 34 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  listHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  listHeaderIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: Colors.successSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  listHeaderBody: { flex: 1 },
  listSubtitle: { color: Colors.subtext, fontSize: 13, marginTop: 3 },
  title: { fontSize: 24, fontWeight: '800', color: Colors.text },
  formIntro: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  formIntroIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: Colors.successSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  formIntroCopy: { flex: 1 },
  formEyebrow: { color: Colors.success, fontSize: 13, fontWeight: '800', marginBottom: 2 },
  formHint: { color: Colors.subtext, fontSize: 13, lineHeight: 19, marginTop: 3 },
  section: { fontSize: 16, fontWeight: '800', color: '#3F8064', marginTop: 14, marginBottom: 8 },
  card: {
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    borderRadius: 18,
    marginTop: 10,
    gap: 5,
  },
  cardTitleRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  cardIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: Colors.successSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 9,
  },
  name: { flex: 1, color: Colors.text, fontSize: 18, fontWeight: '700' },
  cardText: { color: Colors.text, lineHeight: 20 },
  cardHint: { color: Colors.subtext, fontSize: 12 },
  label: {
    color: Colors.text,
    fontSize: FORM_FIELD_LABEL_FONT_SIZE,
    fontWeight: FORM_FIELD_LABEL_FONT_WEIGHT,
    marginBottom: FORM_FIELD_LABEL_MARGIN_BOTTOM,
    marginTop: FORM_FIELD_LABEL_MARGIN_TOP,
  },
  input: {
    fontSize: FORM_FIELD_FONT_SIZE,
    backgroundColor: Colors.surface,
    color: Colors.text,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: FORM_FIELD_RADIUS,
    padding: 14,
    minHeight: FORM_FIELD_HEIGHT,
  },
  options: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginVertical: 10 },
  chip: {
    paddingHorizontal: 14,
    minHeight: 44,
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: Colors.surfaceSoft,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  selected: { backgroundColor: Colors.successSoft, borderColor: Colors.success },
  primary: {
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'center',
    backgroundColor: Colors.primary,
    padding: 14,
    minHeight: FORM_BUTTON_HEIGHT,
    borderRadius: FORM_BUTTON_RADIUS,
    alignItems: 'center',
    marginVertical: 10,
  },
  primaryText: { color: '#fff', fontWeight: '700' },
  empty: { color: Colors.text, fontWeight: '700', textAlign: 'center' },
  error: { color: '#b42318' },
  action: { color: Colors.success, textAlign: 'center' },
  secondaryAction: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: Colors.success,
    borderRadius: 14,
    justifyContent: 'center',
    marginVertical: 4,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  deleteButton: {
    alignSelf: 'center',
    minHeight: 44,
    minWidth: 72,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  secondary: {
    borderWidth: 1,
    borderColor: Colors.success,
    borderRadius: 18,
    minHeight: 48,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 4,
  },
  secondaryText: { color: Colors.success, fontWeight: '700' },
  delete: { color: '#b42318', textAlign: 'center' },
  reminderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 8,
    backgroundColor: Colors.surfaceSoft,
    borderRadius: 14,
    paddingHorizontal: 10,
  },
  reminderAction: {
    minHeight: 44,
    minWidth: 52,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  reminderHint: { color: '#6A5A50', flex: 1 },
  notice: { color: '#666', marginTop: 14 },
  detailHero: { flexDirection: 'row', alignItems: 'center', marginBottom: 18 },
  detailHeroIcon: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: Colors.successSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 13,
  },
  detailHeroCopy: { flex: 1 },
  detailGroup: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 18,
    overflow: 'hidden',
  },
  detailRow: {
    minHeight: 54,
    paddingHorizontal: 16,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.border,
  },
  detailRowMultiline: { alignItems: 'flex-start' },
  detailLabel: { color: Colors.subtext, fontSize: 14, fontWeight: '700', paddingRight: 14 },
  detailValue: { color: Colors.text, fontSize: 15, fontWeight: '600', flex: 1, textAlign: 'right' },
  detailValueMultiline: { lineHeight: 21 },
  actionRow: { flexDirection: 'row', gap: 10, marginTop: 18 },
  actionButton: { flex: 1, marginVertical: 0 },
});
