import React, { useCallback, useState } from 'react';
import { Alert, SafeAreaView, ScrollView, Share, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { useAuth } from '../contexts/AuthContext';
import { usePet } from '../contexts/PetContext';
import { getVetVisitBrief, VetVisitBrief } from '../services/aiService';
export default function PreVetSummaryScreen() {
  const { session }=useAuth(); const { selectedPet }=usePet(); const [range,setRange]=useState<7|30|90>(7); const [brief,setBrief]=useState<VetVisitBrief|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const load=useCallback(async()=>{ if(!session?.userId||!selectedPet)return; setLoading(true);setError('');try{setBrief(await getVetVisitBrief(session.userId,selectedPet.id,range));}catch(e){setError((e as Error).message||'摘要載入失敗');}finally{setLoading(false);}},[session?.userId,selectedPet,range]); useFocusEffect(useCallback(()=>{load();},[load]));
  const share=async()=>{if(!brief)return;try{await Share.share({message:`${brief.pet.name||selectedPet?.name||'毛孩'} 就醫前摘要\n${brief.generatedSummary}\n\n${brief.keyObservations.join('\n')}\n\n${brief.disclaimer}`});}catch(e){Alert.alert('分享失敗',(e as Error).message);}};
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>就醫前摘要</Text><Text style={s.subtitle}>{selectedPet?.name||'目前毛孩'}</Text><View style={s.row}>{([7,30,90] as const).map(v=><TouchableOpacity key={v} accessibilityRole="button" accessibilityLabel={`查看最近 ${v} 天資料`} style={[s.chip,range===v&&s.active]} onPress={()=>setRange(v)}><Text>{v} 天</Text></TouchableOpacity>)}</View>{loading&&<Text>正在整理紀錄…</Text>}{error&&<Text style={s.error}>{error}</Text>}{brief&&!loading&&<><Text style={s.heading}>摘要</Text><Text>{brief.generatedSummary}</Text><Text style={s.heading}>給獸醫的重點</Text>{brief.keyObservations.map(x=><Text key={x} style={s.item}>• {x}</Text>)}<Text style={s.heading}>資料範圍</Text><Text>體重 {brief.dataCoverage.weightRecords} 筆・日常 {brief.dataCoverage.dailyLogs} 筆・健康異常 {brief.dataCoverage.healthEvents} 筆・就醫 {brief.dataCoverage.medicalVisits} 筆</Text><Text style={s.heading}>目前用藥</Text><Text>{brief.activeMedications.length?brief.activeMedications.map(x=>x.name).join('、'):'目前沒有進行中的用藥紀錄'}</Text><TouchableOpacity accessibilityRole="button" accessibilityLabel="分享就醫前摘要" style={s.button} onPress={share}><Text style={s.buttonText}>分享摘要</Text></TouchableOpacity><Text style={s.disclaimer}>{brief.disclaimer}</Text></>}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#FFFDF9'},content:{padding:20,gap:10},title:{fontSize:24,fontWeight:'700'},subtitle:{color:'#766F69'},row:{flexDirection:'row',gap:8},chip:{padding:10,borderRadius:14,backgroundColor:'#F1E8DD'},active:{backgroundColor:'#D9BFA5'},heading:{fontSize:17,fontWeight:'700',marginTop:12},item:{lineHeight:22},button:{marginTop:18,padding:14,borderRadius:14,backgroundColor:'#8B6B52',alignItems:'center'},buttonText:{color:'#FFF',fontWeight:'600'},disclaimer:{fontSize:12,color:'#81776F',marginTop:16},error:{color:'#B4473F'}});
