import { StyleSheet } from 'react-native';

import { Colors } from '../../constants/Colors';

export const weightListStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  content: { padding: 18, paddingBottom: 34 },
  flex: { flex: 1, minWidth: 0 },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.background,
    padding: 28,
  },
  stateTitle: { color: Colors.text, fontSize: 21, fontWeight: '800' },
  stateText: { color: Colors.subtext, textAlign: 'center', marginTop: 8 },
  retry: {
    backgroundColor: Colors.primary,
    borderRadius: 13,
    paddingHorizontal: 22,
    paddingVertical: 11,
    marginTop: 18,
  },
  retryText: { color: '#FFF', fontWeight: '800' },
  primary: {
    backgroundColor: Colors.primary,
    padding: 14,
    minHeight: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  primaryText: { color: '#FFF', fontWeight: '800' },
  listContext: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 2,
    marginTop: 16,
  },
  contextIcon: {
    width: 38,
    height: 38,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.successSoft,
  },
  contextTitle: { color: Colors.text, fontSize: 15, fontWeight: '800' },
  contextHint: { color: Colors.subtext, fontSize: 12, marginTop: 2 },
  summary: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 18,
    padding: 18,
    marginTop: 14,
  },
  caption: { color: Colors.subtext },
  current: { color: Colors.text, fontSize: 30, fontWeight: '800', marginTop: 4 },
  measuredAt: { color: Colors.subtext, marginTop: 6 },
  diff: { color: Colors.text, fontWeight: '700', marginTop: 9 },
  increased: { color: '#B56A3B' },
  decreased: { color: '#4F8A6D' },
  heading: { color: Colors.text, fontSize: 20, fontWeight: '800', marginTop: 22, marginBottom: 12 },
  filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  filter: {
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 11,
    minHeight: 44,
  },
  filterActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  filterText: { color: Colors.text, fontSize: 12, fontWeight: '600' },
  filterTextActive: { color: '#FFF' },
  chartCard: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 18,
    padding: 12,
  },
  chartCanvas: { height: 165, position: 'relative' },
  axisLabel: { position: 'absolute', left: 0, width: 42, color: Colors.subtext, fontSize: 10 },
  axisLine: { position: 'absolute', width: 1, backgroundColor: Colors.border },
  horizontalAxis: { position: 'absolute', height: 1, backgroundColor: Colors.border },
  chartLine: { position: 'absolute', height: 2, borderRadius: 1, backgroundColor: Colors.primary },
  chartPoint: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.text,
  },
  xLabels: { flexDirection: 'row', justifyContent: 'space-between', paddingLeft: 42, marginTop: 3 },
  xLabel: { color: Colors.subtext, fontSize: 10, maxWidth: '48%' },
  xLabelRight: { textAlign: 'right' },
  emptyBox: { alignItems: 'center', paddingVertical: 28 },
  emptyHint: { color: '#887A6D', fontSize: 13, marginTop: 6, textAlign: 'center' },
  empty: {
    color: Colors.subtext,
    textAlign: 'center',
    backgroundColor: Colors.surface,
    borderRadius: 18,
    padding: 25,
  },
  card: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  focusCard: { borderColor: Colors.primary, borderWidth: 2 },
  sourceMissing: { color: '#C55B5B', textAlign: 'center', marginVertical: 10 },
  recordContent: { flex: 1, paddingRight: 12 },
  weight: { color: Colors.text, fontSize: 19, fontWeight: '800' },
  date: { color: Colors.subtext, marginTop: 3 },
  notes: { color: Colors.text, marginTop: 7 },
  actions: { gap: 12, alignItems: 'flex-end' },
  rowAction: {
    minHeight: 44,
    minWidth: 56,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  link: { color: Colors.primary, fontWeight: '700' },
  delete: { color: '#E57373', fontWeight: '700' },
});
