/** 用途：疫苗功能共用樣式。 */
import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/Colors';
import {
  FORM_BUTTON_HEIGHT,
  FORM_BUTTON_RADIUS,
  FORM_FIELD_HEIGHT,
  FORM_FIELD_FONT_SIZE,
  FORM_FIELD_LABEL_FONT_SIZE,
  FORM_FIELD_LABEL_FONT_WEIGHT,
  FORM_FIELD_LABEL_MARGIN_BOTTOM,
  FORM_FIELD_LABEL_MARGIN_TOP,
  FORM_FIELD_RADIUS,
  FORM_PAGE_HORIZONTAL_PADDING,
} from '../../constants/FormTokens';

export const vaccinationStyles = StyleSheet.create({
  emptyBox: { alignItems: 'center', paddingVertical: 28 },
  emptyArtwork: { width: 82, height: 76, marginBottom: 10 },
  emptyHint: { color: '#887A6D', fontSize: 13, marginTop: 6, textAlign: 'center' },
  page: { paddingHorizontal: FORM_PAGE_HORIZONTAL_PADDING, paddingTop: 18, paddingBottom: 34 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  listHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  listHeaderIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: Colors.successSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  listHeaderBody: { flex: 1 },
  listSubtitle: { color: Colors.subtext, fontSize: 13, marginTop: 3 },
  title: { fontSize: 24, fontWeight: '800', color: Colors.text },
  formIntro: { flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 12 },
  formIntroIcon: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: Colors.successSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formIntroCopy: { flex: 1, minWidth: 0 },
  formEyebrow: { color: Colors.success, fontSize: 12, fontWeight: '800' },
  formHint: { color: Colors.subtext, fontSize: 12, lineHeight: 17, marginTop: 2 },
  card: {
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    borderRadius: 18,
    marginTop: 12,
    gap: 5,
  },
  cardTitleRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  cardIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: Colors.successSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 9,
  },
  name: { flex: 1, color: Colors.text, fontSize: 18, fontWeight: '700' },
  cardText: { color: Colors.text, lineHeight: 20 },
  cardMeta: { color: Colors.primary, fontWeight: '700' },
  label: {
    color: Colors.text,
    fontSize: FORM_FIELD_LABEL_FONT_SIZE,
    fontWeight: FORM_FIELD_LABEL_FONT_WEIGHT,
    marginBottom: FORM_FIELD_LABEL_MARGIN_BOTTOM,
    marginTop: FORM_FIELD_LABEL_MARGIN_TOP,
  },
  input: {
    fontSize: FORM_FIELD_FONT_SIZE,
    backgroundColor: Colors.surface,
    color: Colors.text,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: FORM_FIELD_RADIUS,
    padding: 14,
    minHeight: FORM_FIELD_HEIGHT,
    marginBottom: 10,
  },
  primary: {
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'center',
    backgroundColor: Colors.primary,
    padding: 14,
    minHeight: FORM_BUTTON_HEIGHT,
    borderRadius: FORM_BUTTON_RADIUS,
    alignItems: 'center',
    marginVertical: 10,
  },
  primaryText: { color: '#fff', fontWeight: '700' },
  detailHero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 14,
  },
  detailHeroIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: Colors.successSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailHeroCopy: { flex: 1, minWidth: 0 },
  detailTitle: { color: Colors.text, fontSize: 18, fontWeight: '800' },
  detailDate: { color: Colors.subtext, fontSize: 12, marginTop: 3 },
  detailGroup: {
    marginTop: 14,
    backgroundColor: Colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: 'hidden',
  },
  detailRow: {
    paddingHorizontal: 15,
    paddingVertical: 13,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.border,
  },
  detailLabel: { color: Colors.subtext, fontSize: 12 },
  detailValue: { color: Colors.text, lineHeight: 20, marginTop: 4 },
  actionRow: { flexDirection: 'row', gap: 10, marginTop: 16 },
  actionButton: {
    flex: 1,
    height: 44,
    minHeight: 44,
    marginVertical: 0,
    paddingVertical: 0,
    borderRadius: 12,
  },
  secondary: {
    borderWidth: 1,
    borderColor: Colors.success,
    borderRadius: 18,
    minHeight: 52,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryText: { color: Colors.success, fontWeight: '700' },
  empty: { color: Colors.text, fontWeight: '700', textAlign: 'center' },
  error: { color: '#b42318' },
  deleteButton: {
    alignSelf: 'center',
    minHeight: 44,
    minWidth: 72,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginTop: 8,
  },
  delete: { color: '#b42318', textAlign: 'center', fontWeight: '700' },
});
