/** 用途：就醫前摘要頁與表格共用樣式。 */
import { StyleSheet } from 'react-native';
import { Colors } from '../../../constants/Colors';

export const preVetStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  content: { padding: 20, paddingBottom: 36, gap: 18 },
  title: { fontSize: 26, fontWeight: '800', color: Colors.text },
  subtitle: { marginTop: 6, color: Colors.subtext, fontSize: 15, lineHeight: 22 },
  rangeRow: { flexDirection: 'row', gap: 8 },
  chip: {
    paddingVertical: 9,
    paddingHorizontal: 13,
    borderRadius: 16,
    backgroundColor: Colors.peachSoft,
  },
  activeChip: { backgroundColor: Colors.primary },
  chipText: { color: Colors.subtext, fontWeight: '700' },
  activeChipText: { color: Colors.surface },
  selector: {
    borderRadius: 18,
    backgroundColor: Colors.surfaceSoft,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 16,
    gap: 8,
  },
  selectorTitle: { color: Colors.text, fontSize: 17, fontWeight: '800' },
  selectorHint: { color: Colors.subtext, fontSize: 13, lineHeight: 19 },
  optionWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  option: {
    paddingVertical: 8,
    paddingHorizontal: 11,
    borderRadius: 14,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  optionActive: { backgroundColor: Colors.successSoft, borderColor: Colors.success },
  optionText: { color: Colors.subtext, fontWeight: '600' },
  optionTextActive: { color: Colors.success },
  applyButton: {
    alignSelf: 'flex-start',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: Colors.primary,
  },
  applyButtonText: { color: Colors.surface, fontWeight: '700' },
  loading: { color: Colors.subtext, paddingVertical: 24, textAlign: 'center' },
  error: { color: Colors.danger, lineHeight: 20 },
  section: { gap: 8 },
  heading: { color: Colors.text, fontSize: 19, fontWeight: '800' },
  table: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 18,
    overflow: 'hidden',
  },
  tableRow: {
    flexDirection: 'row',
    gap: 12,
    padding: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.border,
  },
  rowLabel: { width: 76, color: Colors.subtext, fontSize: 13, lineHeight: 20 },
  rowValue: { flex: 1, color: Colors.text, fontSize: 14, fontWeight: '600', lineHeight: 20 },
  flexValue: { flex: 1, gap: 3 },
  rowDetail: { color: Colors.subtext, fontSize: 13, lineHeight: 19 },
  item: { color: Colors.text, fontSize: 15, lineHeight: 23 },
  questionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.border,
  },
  questionIcon: {
    width: 25,
    height: 25,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.successSoft,
    marginTop: 1,
  },
  questionText: {
    flex: 1,
    minWidth: 0,
    flexShrink: 1,
    color: Colors.text,
    fontSize: 14,
    lineHeight: 21,
  },
  empty: { padding: 16, color: Colors.subtext, textAlign: 'center' },
  aiButton: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.primarySoft,
    backgroundColor: Colors.surfaceSoft,
    padding: 15,
    alignItems: 'center',
    gap: 3,
  },
  disabledButton: { opacity: 0.6 },
  aiButtonText: { color: Colors.primary, fontSize: 16, fontWeight: '800' },
  aiButtonHint: { color: Colors.subtext, fontSize: 12 },
  aiGroup: { gap: 8 },
  aiDisclosure: {
    minHeight: 60,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 16,
    backgroundColor: Colors.surfaceSoft,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  aiDisclosureTitle: { color: Colors.text, fontSize: 14, fontWeight: '800' },
  aiDisclosureHint: { color: Colors.subtext, fontSize: 12, marginTop: 3 },
  aiDisclosureContent: { flex: 1 },
  aiTool: {
    borderRadius: 16,
    backgroundColor: Colors.surfaceSoft,
    padding: 14,
    gap: 10,
  },
  aiToolDescription: { color: Colors.subtext, fontSize: 13, lineHeight: 19 },
  sourceNotice: {
    borderRadius: 15,
    backgroundColor: Colors.peachSoft,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  sourceNoticeTitle: { color: Colors.primary, fontSize: 13, fontWeight: '800' },
  sourceNoticeText: { color: Colors.subtext, fontSize: 13, lineHeight: 19 },
  shareButton: {
    padding: 15,
    borderRadius: 16,
    backgroundColor: Colors.primary,
    alignItems: 'center',
  },
  shareButtonText: { color: Colors.surface, fontWeight: '800', fontSize: 16 },
  disclaimer: { color: Colors.subtext, fontSize: 12, lineHeight: 18 },
});
